name: Build Installers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Build DMG
        run: mvn clean package "-Djpackage.type=exe"
      - uses: actions/upload-artifact@v4
        with:
          name: jsontool-dmg
          path: target/installer/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Build EXE
        run: mvn clean package -Djpackage.type=exe
      - uses: actions/upload-artifact@v4
        with:
          name: jsontool-exe
          path: target/installer/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Build AppImage
        run: mvn clean package -Djpackage.type=app-image
      - uses: actions/upload-artifact@v4
        with:
          name: jsontool-appimage
          path: target/installer/**
