name: Build JSONTool

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Build DMG
        run: |
          mvn -B clean package -Djpackage.type=dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: jsontool-dmg
          path: target/installer/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Build EXE
        run: |
          mvn -B clean package -Djpackage.type=exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: jsontool-exe
          path: target/installer/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Build portable app image
        run: |
          mvn -B clean package -Djpackage.type=app-image

      - name: Upload app-image
        uses: actions/upload-artifact@v4
        with:
          name: jsontool-appimage
          path: target/installer/**
